import '../models/models.dart';

/// Dữ liệu gốc của Wildan. Dùng để nạp (seed) lên Firestore lần đầu,
/// đồng thời làm dữ liệu dự phòng OFFLINE khi chưa có mạng.
class SeedData {
  // ---------------- THƯ VIỆN 10 LOÀI ----------------
  static final List<Species> species = [
    Species(
      id: 'mang_tre',
      emoji: '🎋',
      name: 'Măng Tre',
      scientificName: 'Bambusa spp.',
      type: 'plant',
      category: 'edible',
      description: 'Chồi non của cây tre, giàu dinh dưỡng, dễ tìm trong rừng Cúc Phương.',
      identification: [
        'Chồi nhọn mọc từ gốc tre',
        'Vỏ ngoài nhiều lông tơ màu nâu',
        'Bên trong trắng ngà, giòn',
        'Mọc thành cụm quanh bụi tre',
      ],
      usage: 'Luộc kỹ 2 lần để loại bỏ độc tố tự nhiên trước khi ăn. Có thể nướng.',
      warning: 'Măng sống chứa cyanide nhẹ — BẮT BUỘC luộc chín.',
      habitat: 'Bụi tre ven suối, sườn đồi',
    ),
    Species(
      id: 'la_dong',
      emoji: '🍃',
      name: 'Lá Dong',
      scientificName: 'Phrynium placentarium',
      type: 'plant',
      category: 'useful',
      description: 'Lá to bản, dai, rất hữu dụng để làm mái che và gói thức ăn.',
      identification: [
        'Lá to hình bầu dục, dài 30-60cm',
        'Mặt lá xanh đậm bóng',
        'Gân lá song song rõ',
        'Mọc thành bụi nơi ẩm',
      ],
      usage: 'Lợp mái lều, gói thực phẩm giữ sạch, hứng nước mưa.',
      warning: '',
      habitat: 'Nơi ẩm thấp, ven suối, dưới tán rừng',
    ),
    Species(
      id: 'nam_rom',
      emoji: '🍄',
      name: 'Nấm Rơm',
      scientificName: 'Volvariella volvacea',
      type: 'plant',
      category: 'edible',
      description: 'Nấm ăn được phổ biến, mọc trên thân cây mục và rơm rạ.',
      identification: [
        'Mũ nấm tròn màu nâu xám',
        'Có bao gốc (volva) ở chân',
        'Thịt nấm trắng',
        'Mọc thành cụm trên gỗ mục',
      ],
      usage: 'Nấu chín kỹ trước khi ăn.',
      warning: '⚠️ CHỈ ăn nếu 100% chắc chắn — nhiều nấm độc trông giống hệt!',
      habitat: 'Thân cây mục, đất giàu mùn',
    ),
    Species(
      id: 'dau_rung',
      emoji: '🫐',
      name: 'Dâu Rừng',
      scientificName: 'Rubus spp.',
      type: 'plant',
      category: 'edible',
      description: 'Quả mọng nhỏ màu đỏ/tím, vị chua ngọt, bổ sung vitamin C.',
      identification: [
        'Quả mọng kết từ nhiều hạt nhỏ',
        'Thân có gai nhỏ',
        'Lá răng cưa mọc cách',
        'Quả chín màu đỏ sẫm đến tím',
      ],
      usage: 'Ăn trực tiếp khi chín, bổ sung nước và vitamin.',
      warning: 'Chỉ ăn quả chín, tránh quả còn xanh.',
      habitat: 'Bìa rừng, nơi nhiều nắng',
    ),
    Species(
      id: 'cay_la_ngon_duoc',
      emoji: '🌿',
      name: 'Cây Lá Sát Trùng',
      scientificName: 'Eupatorium odoratum',
      type: 'plant',
      category: 'medicine',
      description: 'Cây dược liệu dùng sát trùng vết thương và đuổi muỗi.',
      identification: [
        'Lá hình tam giác, mép răng cưa',
        'Có mùi hắc đặc trưng khi vò',
        'Hoa nhỏ màu trắng/tím nhạt',
        'Thân mềm cao 1-2m',
      ],
      usage: 'Vò lá đắp lên vết thương để cầm máu, sát trùng. Đốt lá đuổi muỗi.',
      warning: 'Không uống. Chỉ dùng ngoài da.',
      habitat: 'Ven đường mòn, đất hoang',
    ),
    Species(
      id: 'thong_tre',
      emoji: '🌲',
      name: 'Cây Thông Tre',
      scientificName: 'Podocarpus spp.',
      type: 'plant',
      category: 'useful',
      description: 'Gỗ chắc, nhựa và lá khô làm mồi lửa rất tốt.',
      identification: [
        'Lá kim dẹt dài',
        'Vỏ cây nâu xám nứt dọc',
        'Có nhựa thơm',
        'Cây gỗ lớn thẳng',
      ],
      usage: 'Lá khô và nhựa làm mồi lửa; gỗ làm khung lều, công cụ.',
      warning: '',
      habitat: 'Rừng núi đá vôi Cúc Phương',
    ),
    Species(
      id: 'ran_ho_mang',
      emoji: '🐍',
      name: 'Rắn Hổ Mang',
      scientificName: 'Naja spp.',
      type: 'animal',
      category: 'danger',
      description: 'Rắn độc cực kỳ nguy hiểm, cần huyết thanh khẩn cấp khi bị cắn.',
      identification: [
        'Bành mang khi đe doạ',
        'Thân dài, màu nâu/đen',
        'Đầu hình bầu dục',
        'Phát tiếng "phù" cảnh báo',
      ],
      usage: '',
      warning: '🔴 CỰC KỲ NGUY HIỂM. Bị cắn: giữ bình tĩnh, để vùng cắn thấp hơn tim, KHÔNG cắt/hút độc, gọi 115 NGAY.',
      habitat: 'Bụi rậm, hang đá, gần nguồn nước',
    ),
    Species(
      id: 'ong_rung',
      emoji: '🐝',
      name: 'Ong Rừng',
      scientificName: 'Apis dorsata',
      type: 'animal',
      category: 'danger',
      description: 'Ong rừng hung dữ, đốt tập thể có thể gây sốc phản vệ.',
      identification: [
        'Tổ lớn treo trên cành cao/vách đá',
        'Thân vàng đen, to',
        'Bay theo đàn',
        'Tiếng vo ve lớn khi bị quấy',
      ],
      usage: 'Mật ong ăn được nhưng RẤT nguy hiểm khi lấy.',
      warning: '⚠️ Tránh xa tổ ít nhất 50m. Không gây tiếng động/khói gần tổ.',
      habitat: 'Cành cây cao, vách đá',
    ),
    Species(
      id: 'oc_buou_vang',
      emoji: '🐌',
      name: 'Ốc Bươu Vàng',
      scientificName: 'Pomacea canaliculata',
      type: 'animal',
      category: 'edible',
      description: 'Nguồn protein dễ tìm ở vùng nước, ruộng ngập.',
      identification: [
        'Vỏ tròn màu vàng nâu',
        'Trứng màu hồng bám trên cây thủy sinh',
        'Kích thước 3-6cm',
        'Sống ở nước tù, ruộng',
      ],
      usage: 'Luộc/nướng. Bổ sung protein quan trọng.',
      warning: '🔴 BẮT BUỘC nấu chín kỹ — chứa ký sinh trùng nguy hiểm.',
      habitat: 'Ao, suối chảy chậm, ruộng ngập',
    ),
    Species(
      id: 'chau_chau',
      emoji: '🦗',
      name: 'Châu Chấu',
      scientificName: 'Caelifera',
      type: 'animal',
      category: 'edible',
      description: 'Côn trùng giàu protein, dễ bắt, hơn cả thịt bò về dinh dưỡng.',
      identification: [
        'Chân sau dài để nhảy',
        'Màu xanh/nâu',
        'Có cánh',
        'Hoạt động mạnh ban ngày',
      ],
      usage: 'Bỏ chân/cánh, nướng hoặc rang chín. Giàu protein.',
      warning: 'Nấu chín để diệt ký sinh. Tránh con màu sặc sỡ (có thể độc).',
      habitat: 'Đồng cỏ, bụi cây thấp',
    ),
    // ---------- BỔ SUNG THÊM LOÀI ----------
    Species(
      id: 'rau_ma',
      emoji: '🌿',
      name: 'Rau Má',
      scientificName: 'Centella asiatica',
      type: 'plant',
      category: 'edible',
      description: 'Rau dại ăn được, vừa là thực phẩm vừa là dược liệu mát gan, lành vết thương.',
      identification: [
        'Lá hình tròn như đồng xu, mép răng cưa',
        'Bò sát mặt đất theo thân',
        'Mọc nơi ẩm, ven suối',
        'Cuống lá dài mọc từ mắt thân',
      ],
      usage: 'Ăn sống/nấu canh. Giã đắp giúp lành vết thương, hạ sốt.',
      warning: 'Rửa sạch trước khi ăn (có thể nhiễm ký sinh từ nước).',
      habitat: 'Nơi ẩm, ven suối, bãi cỏ',
    ),
    Species(
      id: 'chuoi_rung',
      emoji: '🍌',
      name: 'Chuối Rừng',
      scientificName: 'Musa acuminata',
      type: 'plant',
      category: 'useful',
      description: 'Cây đa dụng: quả ăn được, thân chứa nước, lá làm mái che/gói đồ.',
      identification: [
        'Thân giả mọng nước, cao 2-4m',
        'Lá to bản dài',
        'Buồng quả nhỏ nhiều hạt',
        'Mọc thành cụm nơi ẩm',
      ],
      usage: 'Quả chín ăn được; lõi thân non ăn/uống nước; lá lợp mái, gói thức ăn.',
      warning: 'Quả rừng nhiều hạt cứng, ăn cẩn thận.',
      habitat: 'Thung lũng ẩm, ven suối',
    ),
    Species(
      id: 'cay_sung',
      emoji: '🌳',
      name: 'Cây Sung',
      scientificName: 'Ficus racemosa',
      type: 'plant',
      category: 'edible',
      description: 'Quả sung mọc thành chùm trên thân, ăn được, phổ biến ở rừng Cúc Phương.',
      identification: [
        'Quả mọc chùm bám thân/cành lớn',
        'Quả tròn xanh chuyển đỏ khi chín',
        'Lá hình bầu dục',
        'Cây gỗ lớn, nhiều nhựa trắng',
      ],
      usage: 'Quả ăn sống/luộc; lá non ăn kèm. Nhựa cầm máu vết thương nhỏ.',
      warning: '',
      habitat: 'Ven suối, đất ẩm',
    ),
    Species(
      id: 'gung_rung',
      emoji: '🫚',
      name: 'Gừng Rừng',
      scientificName: 'Zingiber spp.',
      type: 'plant',
      category: 'medicine',
      description: 'Củ gừng dại có tính ấm, dùng giữ ấm cơ thể, chống buồn nôn, sát khuẩn.',
      identification: [
        'Lá thuôn dài như lá sả',
        'Củ thơm cay đặc trưng khi bẻ',
        'Mọc cụm nơi đất ẩm',
        'Hoa mọc từ gốc',
      ],
      usage: 'Nhai/đun nước uống giữ ấm, giảm buồn nôn, chống lạnh.',
      warning: 'Phân biệt với cây giống — chỉ dùng khi có mùi gừng rõ.',
      habitat: 'Tán rừng ẩm, ven suối',
    ),
    Species(
      id: 'nam_doc',
      emoji: '🍄‍🟫',
      name: 'Nấm Độc Tán Trắng',
      scientificName: 'Amanita verna',
      type: 'plant',
      category: 'danger',
      description: 'Nấm cực độc, chỉ một lượng nhỏ có thể gây tử vong. TUYỆT ĐỐI không ăn.',
      identification: [
        'Mũ trắng tinh, nhẵn',
        'Có vòng cổ ở cuống',
        'Có bao gốc phình to',
        'Phiến nấm trắng',
      ],
      usage: '',
      warning: '🔴 CỰC ĐỘC — gây suy gan, tử vong. KHÔNG chạm, KHÔNG ăn dù nấu chín.',
      habitat: 'Đất rừng ẩm, dưới tán cây',
    ),
    Species(
      id: 'ca_suoi',
      emoji: '🐟',
      name: 'Cá Suối',
      scientificName: 'Various spp.',
      type: 'animal',
      category: 'edible',
      description: 'Nguồn protein dồi dào ở các suối Cúc Phương, dễ bắt bằng bẫy đơn giản.',
      identification: [
        'Thân nhỏ, bơi theo đàn',
        'Sống nước trong, chảy',
        'Ẩn dưới đá, hốc',
        'Hoạt động mạnh sáng sớm/chiều',
      ],
      usage: 'Bắt bằng bẫy đá/lưới tay. Nướng hoặc nấu chín kỹ.',
      warning: 'Nấu chín để diệt ký sinh trùng.',
      habitat: 'Suối nước trong, chảy',
    ),
    Species(
      id: 'tac_ke',
      emoji: '🦎',
      name: 'Tắc Kè',
      scientificName: 'Gekko gecko',
      type: 'animal',
      category: 'edible',
      description: 'Bò sát phổ biến, thịt ăn được, là nguồn protein khẩn cấp.',
      identification: [
        'Da xám xanh đốm cam',
        'Kêu "tắc-kè" đặc trưng',
        'Bám tường/vách đá, thân cây',
        'Hoạt động ban đêm',
      ],
      usage: 'Làm sạch, nướng chín kỹ. Nguồn protein.',
      warning: 'Cắn đau, bắt cẩn thận. Nấu thật chín.',
      habitat: 'Vách đá, hốc cây, hang',
    ),
    Species(
      id: 've_sau',
      emoji: '🪲',
      name: 'Ve Sầu',
      scientificName: 'Cicadidae',
      type: 'animal',
      category: 'edible',
      description: 'Côn trùng giàu đạm, ấu trùng và con non đều ăn được sau khi nấu.',
      identification: [
        'Tiếng kêu vang mùa hè',
        'Cánh trong suốt, thân to',
        'Ấu trùng đào hang dưới đất',
        'Bám thân cây',
      ],
      usage: 'Bắt khi mới lột xác (mềm). Rang/nướng chín. Giàu protein.',
      warning: 'Người dị ứng hải sản nên thận trọng. Nấu chín.',
      habitat: 'Thân cây, đất quanh gốc',
    ),
    Species(
      id: 'con_trung_dom',
      emoji: '🐛',
      name: 'Sâu Tre',
      scientificName: 'Omphisa fuscidentalis',
      type: 'animal',
      category: 'edible',
      description: 'Ấu trùng sống trong thân tre, giàu chất béo và protein.',
      identification: [
        'Màu trắng ngà, mềm',
        'Sống trong lóng tre',
        'Để lại lỗ nhỏ trên thân tre',
        'Dài 2-4cm',
      ],
      usage: 'Lấy từ thân tre, rang/nướng chín. Rất giàu năng lượng.',
      warning: 'Nấu chín trước khi ăn.',
      habitat: 'Bên trong thân cây tre',
    ),
    Species(
      id: 'ran_luc',
      emoji: '🐍',
      name: 'Rắn Lục Đuôi Đỏ',
      scientificName: 'Trimeresurus albolabris',
      type: 'animal',
      category: 'danger',
      description: 'Rắn độc nguy hiểm, màu xanh nguỵ trang giỏi, hay nằm trên cành thấp.',
      identification: [
        'Thân xanh lá, đuôi đỏ nâu',
        'Đầu hình tam giác',
        'Nằm cuộn trên cành cây thấp',
        'Khó phát hiện do nguỵ trang',
      ],
      usage: '',
      warning: '🔴 NGUY HIỂM. Nọc gây rối loạn đông máu. Bị cắn: bất động, giữ thấp hơn tim, gọi 115.',
      habitat: 'Bụi cây, cành thấp gần nước',
    ),
    Species(
      id: 'vat',
      emoji: '🦇',
      name: 'Dơi',
      scientificName: 'Chiroptera',
      type: 'animal',
      category: 'danger',
      description: 'Sống trong hang đá Cúc Phương. Tránh tiếp xúc — nguy cơ truyền bệnh dại/virus.',
      identification: [
        'Treo ngược trong hang tối',
        'Cánh da, bay lúc chạng vạng',
        'Số lượng lớn trong hang',
        'Phân bố dày trên nền hang',
      ],
      usage: '',
      warning: '⚠️ Không chạm, không ăn. Nguy cơ truyền bệnh dại và virus. Tránh hang nhiều dơi.',
      habitat: 'Hang động đá vôi',
    ),
    Species(
      id: 'tac_ke_hoa',
      emoji: '🌺',
      name: 'Hoa Chuối Rừng',
      scientificName: 'Musa balbisiana',
      type: 'plant',
      category: 'edible',
      description: 'Bắp hoa chuối ăn được, bổ sung chất xơ và nước.',
      identification: [
        'Bắp hoa màu đỏ tím, hình búp',
        'Mọc ở đầu buồng chuối',
        'Lá bắc xếp lớp',
        'Bên trong có hoa nhỏ',
      ],
      usage: 'Bóc lá bắc, thái mỏng, ngâm nước rồi luộc/trộn ăn.',
      warning: 'Có nhựa chát — ngâm nước muối/chanh trước khi ăn.',
      habitat: 'Cụm chuối rừng nơi ẩm',
    ),
  ];

  // ---------------- 6 HƯỚNG DẪN SINH TỒN ----------------
  static final List<SurvivalGuide> guides = [
    SurvivalGuide(
      id: 'water',
      emoji: '💧',
      title: 'Nước (Ưu tiên cao nhất)',
      priority: 1,
      color: 'info',
      steps: [
        GuideStep('Tìm nguồn nước: theo dấu vết động vật, côn trùng bay, tiếng nước chảy.'),
        GuideStep('Đánh giá chất lượng: nước trong, chảy thì tốt hơn nước tù.'),
        GuideStep('Lọc sơ bộ bằng cát/than/vải sạch.'),
        GuideStep('Đun sôi tối thiểu 1-3 phút để diệt vi khuẩn.'),
        GuideStep('Bảo quản trong bầu tre/chai sạch.'),
        GuideStep('KHÔNG uống nước biển, nước tiểu, nước có mùi lạ.', isWarning: true),
      ],
      localInfo: 'Cúc Phương: có 3 suối tự nhiên trong bán kính 2km. Theo dấu vết động vật để tìm nguồn nước.',
    ),
    SurvivalGuide(
      id: 'shelter',
      emoji: '🏠',
      title: 'Trú ẩn',
      priority: 2,
      color: 'safe',
      steps: [
        GuideStep('Chọn vị trí an toàn: khô ráo, cao hơn mặt đất, gần nước.'),
        GuideStep('Kiểm tra động vật nguy hiểm (rắn, dơi, ong) trước khi dựng.'),
        GuideStep('Xây khung chữ A từ tre/cành cây.'),
        GuideStep('Lợp mái bằng lá cọ/lá dong (3-4 lớp chống mưa).'),
        GuideStep('Lót nền cách nhiệt bằng lá khô để giữ ấm.'),
        GuideStep('Tránh dựng dưới cây khô có thể gãy đổ.', isWarning: true),
      ],
      localInfo: 'Cúc Phương: nhiều hang đá vôi tự nhiên có thể trú ẩn. Lá cọ và lá dong rất phổ biến.',
    ),
    SurvivalGuide(
      id: 'fire',
      emoji: '🔥',
      title: 'Lửa',
      priority: 3,
      color: 'warning',
      steps: [
        GuideStep('Thu thập vật liệu: mồi lửa (vỏ tre khô), củi nhỏ, củi lớn.'),
        GuideStep('Chuẩn bị bệ lửa an toàn, dọn sạch lá khô xung quanh.'),
        GuideStep('Xếp lửa hình chóp (kỹ thuật "tổ chim").'),
        GuideStep('Đánh lửa bằng diêm, bật lửa hoặc ma sát gỗ.'),
        GuideStep('Duy trì và kiểm soát ngọn lửa.'),
        GuideStep('⚠️ Nguy cơ cháy rừng cao! Tre có thể NỔ khi nóng — giữ khoảng cách.', isWarning: true),
      ],
      localInfo: 'Cúc Phương: mùa khô nguy cơ cháy rừng rất cao. Luôn dập tắt lửa hoàn toàn khi rời đi.',
    ),
    SurvivalGuide(
      id: 'food',
      emoji: '🍎',
      title: 'Thức ăn',
      priority: 4,
      color: 'safe',
      steps: [
        GuideStep('Nhận dạng thực vật ăn được (dùng Thư viện trong app).'),
        GuideStep('Test độc tính 5 bước: da → môi → lưỡi → nuốt nhỏ → chờ 8 giờ.'),
        GuideStep('Tìm protein động vật: côn trùng, ốc, cá.'),
        GuideStep('Nấu chín kỹ để diệt ký sinh trùng.'),
        GuideStep('KHÔNG ăn nấm/quả lạ nếu không chắc chắn 100%.', isWarning: true),
      ],
      localInfo: 'Cúc Phương: 12 loại thực vật ăn được đã xác nhận (măng tre, dâu rừng, nấm rơm...).',
    ),
    SurvivalGuide(
      id: 'navigation',
      emoji: '🧭',
      title: 'Định hướng',
      priority: 5,
      color: 'info',
      steps: [
        GuideStep('Xác định hướng bằng mặt trời (mọc Đông, lặn Tây), sao Bắc Đẩu, rêu (mọc phía Bắc ẩm).'),
        GuideStep('Sử dụng la bàn số và bản đồ offline trong app.'),
        GuideStep('Tạo đánh dấu đường đi: gãy cành, xếp đá.'),
        GuideStep('Theo dòng nước xuống hạ lưu thường dẫn tới khu dân cư.'),
        GuideStep('Ở yên nếu đã báo động cứu hộ — dễ được tìm thấy hơn.'),
        GuideStep('⚠️ Địa hình đá vôi có hố sâu, hang động nguy hiểm — đi cẩn thận.', isWarning: true),
      ],
      localInfo: 'Cúc Phương: địa hình núi đá vôi, nhiều hang động. Theo dấu vết động vật dẫn đến nguồn nước.',
    ),
    SurvivalGuide(
      id: 'rescue',
      emoji: '📡',
      title: 'Cứu hộ',
      priority: 6,
      color: 'danger',
      steps: [
        GuideStep('Chọn vị trí tín hiệu thoáng, dễ nhìn từ trên cao.'),
        GuideStep('Tín hiệu khói (ban ngày): 3 đống lửa tam giác, tạo khói trắng.'),
        GuideStep('Tín hiệu lửa (ban đêm): lửa sáng, thêm nhựa cây.'),
        GuideStep('Tạo chữ SOS/X trên mặt đất (tối thiểu 3m).'),
        GuideStep('Tín hiệu âm thanh: 3 tiếng còi/la hét, lặp mỗi phút.'),
        GuideStep('Phản chiếu ánh sáng bằng gương/kim loại về phía máy bay.'),
      ],
      localInfo: 'Số khẩn cấp: 115 (cấp cứu), 113 (công an), 114 (cứu hỏa). Cung cấp toạ độ GPS cho cứu hộ.',
    ),
  ];

  // ---------------- 5 HƯỚNG DẪN SƠ CỨU ----------------
  static final List<FirstAid> firstAid = [
    FirstAid(
      id: 'bleeding',
      emoji: '🩸',
      title: 'Cắt - Vết thương chảy máu',
      doSteps: [
        'Ấn trực tiếp lên vết thương 10-15 phút',
        'Nâng cao vùng bị thương lên trên tim',
        'Thêm băng đè lên, KHÔNG tháo băng cũ',
      ],
      dontSteps: ['Không tháo băng đã thấm máu', 'Không dùng garô trừ khi mất chi'],
      callEmergency: false,
    ),
    FirstAid(
      id: 'snakebite',
      emoji: '🐍',
      title: 'Rắn - Côn trùng cắn',
      doSteps: [
        'GIỮ BÌNH TĨNH, hạn chế cử động',
        'Giữ vùng bị cắn thấp hơn tim',
        'Tháo nhẫn/vòng gần vết cắn (đề phòng sưng)',
        'Ghi nhớ đặc điểm con vật để báo bác sĩ',
      ],
      dontSteps: [
        '❌ KHÔNG cắt vết thương',
        '❌ KHÔNG hút độc',
        '❌ KHÔNG băng chặt garô',
      ],
      callEmergency: true,
    ),
    FirstAid(
      id: 'fracture',
      emoji: '🦴',
      title: 'Gãy xương - Bong gân',
      doSteps: [
        'Cố định bằng nẹp (cành cây, tre)',
        'Đắp lạnh để giảm sưng',
        'Giữ yên vùng bị thương',
      ],
      dontSteps: ['❌ KHÔNG nắn lại xương', '❌ KHÔNG di chuyển nếu nghi gãy cột sống'],
      callEmergency: false,
    ),
    FirstAid(
      id: 'burn',
      emoji: '🔥',
      title: 'Bỏng',
      doSteps: [
        'Làm mát bằng nước sạch 10-20 phút',
        'Che vết bỏng bằng vải sạch',
        'Uống nhiều nước',
      ],
      dontSteps: [
        '❌ KHÔNG thoa kem, dầu, bơ',
        '❌ KHÔNG làm vỡ phồng nước',
      ],
      callEmergency: false,
    ),
    FirstAid(
      id: 'shock',
      emoji: '☀️',
      title: 'Sốc (choáng) - Ngất - Say nắng',
      doSteps: [
        'Nằm ngửa, nâng chân cao 30cm',
        'Giữ ấm cơ thể',
        'Làm mát nếu say nắng (lau nước mát)',
        'Cho uống nước từ từ nếu còn tỉnh',
      ],
      dontSteps: ['❌ KHÔNG cho uống nếu bất tỉnh', '❌ KHÔNG cho uống rượu/cà phê'],
      callEmergency: true,
    ),
  ];
}
