// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6rps3KK7Yn3tEY4MJVsbKPR1A4L10bpM',
    appId: '1:461635699261:web:21014a15c93e360cd4a054',
    messagingSenderId: '461635699261',
    projectId: 'wildan-app',
    authDomain: 'wildan-app.firebaseapp.com',
    storageBucket: 'wildan-app.firebasestorage.app',
    measurementId: 'G-PXMG57W896',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCk8nMqftiEb5WKEO4Ku1QB54rUsTHvnuQ',
    appId: '1:461635699261:android:d8dabe2e475770e8d4a054',
    messagingSenderId: '461635699261',
    projectId: 'wildan-app',
    storageBucket: 'wildan-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUA6lSePuGboi8QiSs4DE5M-g28lbyinU',
    appId: '1:461635699261:ios:b24c9712fb262bdbd4a054',
    messagingSenderId: '461635699261',
    projectId: 'wildan-app',
    storageBucket: 'wildan-app.firebasestorage.app',
    iosBundleId: 'com.example.wildan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUA6lSePuGboi8QiSs4DE5M-g28lbyinU',
    appId: '1:461635699261:ios:b24c9712fb262bdbd4a054',
    messagingSenderId: '461635699261',
    projectId: 'wildan-app',
    storageBucket: 'wildan-app.firebasestorage.app',
    iosBundleId: 'com.example.wildan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6rps3KK7Yn3tEY4MJVsbKPR1A4L10bpM',
    appId: '1:461635699261:web:0b1d7f9df8cea7eed4a054',
    messagingSenderId: '461635699261',
    projectId: 'wildan-app',
    authDomain: 'wildan-app.firebaseapp.com',
    storageBucket: 'wildan-app.firebasestorage.app',
    measurementId: 'G-HYX5WHV28N',
  );
}
